### ISSUE TITLE
Screenshots for README

### ISSUE THREAD

**Issue by hernanmd** [pharo-ai/data-inspector#1]
![data-inspector-screenshot](https://user-images.githubusercontent.com/4825959/108403782-65a81900-721f-11eb-9264-a2e17231c965.png)

**Comment by Ducasse** [comment]
sweet! I imagine that this is with the new stInspector :).

**Comment by hernanmd** [comment]
Pharo 9 support on the way :)

**Comment by jordanmontt** [comment]
Added one more screenshot
