### ISSUE TITLE
SubclassResponsibility: AISpDataFrameInspector class had the subclass responsibility to implement #defaultSpec

### ISSUE THREAD

**Issue by hernanmd** [pharo-ai/data-inspector#10]
An automatic rewriter in Pharo 10 deleted defaultSpec class methods necessary to work in Pharo 9.
Probably the Baseline should be adapted to load specific Spec packages for both Pharo versions.

**Comment by jordanmontt** [comment]
I will close this because it is a lot of work. And also, Pharo 11 is going to be released very soon so will have to mantain several versions. And, as we discussed in the call, if we are planning to have several tools it is going to be very difficult to mantain the code.
