### ISSUE TITLE
DoIt command is not working

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/data-inspector#12]
If we write something in the inspector, and then press the do it button, it produces an error:
![Capture d’écran 2022-02-28 à 16 37 19](https://user-images.githubusercontent.com/33934979/156012039-960bbc7d-dbb1-4058-a027-db0d5da73ebb.png)

![Capture d’écran 2022-02-28 à 16 37 24](https://user-images.githubusercontent.com/33934979/156012059-43f3d2ac-e9cf-46da-90c1-e2a7c243f9c0.png)

If we press cmd + G, instead of opening another page, is does nothing.
@hernanmd

**Comment by jordanmontt** [comment]
I was digging into this and it is not working because the evaluator is actually a Playground, not an inspector evaluator. I find three possible solutions:

1) Remove the evaluator completely
2) Replace it with the actual inspector evaluator
3) have something like moose inspector

I personally incline to have something like moose inspector, an evaluator that can be hidden:
![Capture d’écran 2022-03-01 à 10 55 59](https://user-images.githubusercontent.com/33934979/156147256-7f8bcb72-4aa8-4719-8783-924b1496565c.png)

![Capture d’écran 2022-03-01 à 10 56 05](https://user-images.githubusercontent.com/33934979/156147271-4d1f6002-f2ae-4ab0-b4eb-b1ceaa3b457c.png)

I can work on this. What do you think?

**Comment by jordanmontt** [comment]
Yes, I agree with what you said. But I think it would be better to have an inspector evaluator instead of a little playground inside.

Having this part:
![Capture d’écran 2022-03-07 à 17 22 18](https://user-images.githubusercontent.com/33934979/157074890-18dc960e-662e-404f-8fea-cc44caffe357.png)

instead of this:
![Capture d’écran 2022-03-07 à 17 22 27](https://user-images.githubusercontent.com/33934979/157074919-64884e70-1768-4ae1-8ebf-2109e1ba9778.png)

**Comment by hernanmd** [comment]
@jordanmontt The idea of using the Playground with the toolbar was to have a space where to add new buttons with functionality for the DataFrame using Commander2. What would be the advantage of adding a flat evaluator and then adding a button bar?

I will send you the notes by Discord

**Comment by jordanmontt** [comment]
Hello Hernán @hernanmd I am not talking about adding a button bar, I am just saying that we should use the same inspector evaluator that is already available in the Inspector. Without any extra buttons.

These are my reasons of why I think that is better to se the inspector evaluator instead of the embedded Playground:

- The 4 buttons of the PlayGround pollutes the UI
- The thing that you said about adding buttons with functionality can be done also with the normal inspector evaluator. Because there is also access to `self`. So, theoretically, with the access to `self` the inspector tab and the Playgound are the same for this context.
- With the embedded PlayGround we cannot do the `meta+G` click with opens a new inspector pane (I am very used to that because I do it all the time, I guess other people are too)
- And finally, as the title of the issue says, if we click on the "Do it" button the debugger is opened with an exception

**Comment by jordanmontt** [comment]
Ok, so according to our discussion, I deleted the other buttons of the toolbar and I put the visualisations into another tool. I removed the dependencies to new tools. The idea is that these tools can run in both Pharo inspector or completely independently of it :)

![Capture d’écran 2022-03-21 à 15 25 44](https://user-images.githubusercontent.com/33934979/159282090-2e73b0c2-808a-463a-9f6b-f5090d63ae73.png)

![Capture d’écran 2022-03-21 à 15 26 20](https://user-images.githubusercontent.com/33934979/159282194-4f408bfa-f3a0-40f4-bf83-febd8b2aea83.png)
