### ISSUE TITLE
Does this belongs to DataFrame repo? [Question]

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/data-inspector#5]
@hernanmd do you think that is better if we include this by default in the DataFrame repo. Because they are heavily related and now the dataframe does not have any inspector tabs (because the new inspector is using spec)

**Comment by hernanmd** [comment]
Now there is a basic inspector for the Pharo >= 10 releases I think it's safe to close, and this inspector could be installed as part of the Pharo AI ecosystem
