### ISSUE TITLE
Data-inspector is not working on Pharo10

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/data-inspector#6]
Now, I am trying to use data-inspector but it is not working. It shows an exception that is caused by roassal.

<img width="995" alt="Capture d’écran 2022-02-25 à 16 48 15" src="https://user-images.githubusercontent.com/33934979/155745001-9eaec4d7-e719-45aa-872f-2fef3ec9a10e.png">

Also, now we have by default in DataFrame the table tab.

<img width="696" alt="Capture d’écran 2022-02-25 à 16 49 34" src="https://user-images.githubusercontent.com/33934979/155745212-e6eeccef-e1b0-4096-8b10-822aa74dd568.png">

I am using Pharo 10.

What do you think @hernanmd ?

**Comment by hernanmd** [comment]
Thanks for reporting Jordan.
Updated with the new Roassal3 class names.
